import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  de: {
    welcome: "Willkommen bei OfficeSuite",
    documents: "Dokumente",
    spreadsheets: "Tabellen",
    presentations: "Präsentationen",
    newDocument: "Neues Dokument",
    newSpreadsheet: "Neue Tabelle",
    newPresentation: "Neue Präsentation",
    recent: "Zuletzt verwendet",
    favorites: "Favoriten",
    settings: "Einstellungen",
    language: "Sprache",
    theme: "Design",
    light: "Hell",
    dark: "Dunkel",
    activate: "Aktivieren",
    productKey: "Produktschlüssel",
    enterKey: "Produktschlüssel eingeben",
    activateNow: "Jetzt aktivieren",
    invalidKey: "Ungültiger Produktschlüssel",
    activated: "Aktiviert",
    save: "Speichern",
    delete: "Löschen",
    rename: "Umbenennen",
    cancel: "Abbrechen",
    create: "Erstellen",
    title: "Titel",
    untitled: "Unbenannt",
    allDocuments: "Alle Dokumente",
    home: "Startseite",
    editor: "Editor",
    logout: "Abmelden",
    activationRequired: "Aktivierung erforderlich",
    activationDesc: "Bitte geben Sie Ihren Produktschlüssel ein, um OfficeSuite zu aktivieren.",
    keyUsed: "Dieser Schlüssel wurde bereits verwendet",
    activationSuccess: "Erfolgreich aktiviert!",
    search: "Suchen...",
    noDocuments: "Keine Dokumente vorhanden",
    createFirst: "Erstellen Sie Ihr erstes Dokument",
    lastModified: "Zuletzt geändert",
    type: "Typ",
    bold: "Fett",
    italic: "Kursiv",
    underline: "Unterstrichen",
    alignLeft: "Linksbündig",
    alignCenter: "Zentriert",
    alignRight: "Rechtsbündig",
    addRow: "Zeile hinzufügen",
    addColumn: "Spalte hinzufügen",
    addSlide: "Folie hinzufügen",
    slide: "Folie",
    formula: "Formel",
    back: "Zurück",
    saving: "Speichern...",
    saved: "Gespeichert",
    german: "Deutsch",
    english: "Englisch",
    french: "Französisch",
    spanish: "Spanisch",
    italian: "Italienisch"
  },
  en: {
    welcome: "Welcome to OfficeSuite",
    documents: "Documents",
    spreadsheets: "Spreadsheets",
    presentations: "Presentations",
    newDocument: "New Document",
    newSpreadsheet: "New Spreadsheet",
    newPresentation: "New Presentation",
    recent: "Recent",
    favorites: "Favorites",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    activate: "Activate",
    productKey: "Product Key",
    enterKey: "Enter product key",
    activateNow: "Activate Now",
    invalidKey: "Invalid product key",
    activated: "Activated",
    save: "Save",
    delete: "Delete",
    rename: "Rename",
    cancel: "Cancel",
    create: "Create",
    title: "Title",
    untitled: "Untitled",
    allDocuments: "All Documents",
    home: "Home",
    editor: "Editor",
    logout: "Logout",
    activationRequired: "Activation Required",
    activationDesc: "Please enter your product key to activate OfficeSuite.",
    keyUsed: "This key has already been used",
    activationSuccess: "Successfully activated!",
    search: "Search...",
    noDocuments: "No documents yet",
    createFirst: "Create your first document",
    lastModified: "Last modified",
    type: "Type",
    bold: "Bold",
    italic: "Italic",
    underline: "Underline",
    alignLeft: "Align left",
    alignCenter: "Center",
    alignRight: "Align right",
    addRow: "Add row",
    addColumn: "Add column",
    addSlide: "Add slide",
    slide: "Slide",
    formula: "Formula",
    back: "Back",
    saving: "Saving...",
    saved: "Saved",
    german: "German",
    english: "English",
    french: "French",
    spanish: "Spanish",
    italian: "Italian"
  },
  fr: {
    welcome: "Bienvenue sur OfficeSuite",
    documents: "Documents",
    spreadsheets: "Feuilles de calcul",
    presentations: "Présentations",
    newDocument: "Nouveau document",
    newSpreadsheet: "Nouvelle feuille",
    newPresentation: "Nouvelle présentation",
    recent: "Récent",
    favorites: "Favoris",
    settings: "Paramètres",
    language: "Langue",
    theme: "Thème",
    light: "Clair",
    dark: "Sombre",
    activate: "Activer",
    productKey: "Clé de produit",
    enterKey: "Entrez la clé",
    activateNow: "Activer maintenant",
    invalidKey: "Clé de produit invalide",
    activated: "Activé",
    save: "Enregistrer",
    delete: "Supprimer",
    rename: "Renommer",
    cancel: "Annuler",
    create: "Créer",
    title: "Titre",
    untitled: "Sans titre",
    allDocuments: "Tous les documents",
    home: "Accueil",
    editor: "Éditeur",
    logout: "Déconnexion",
    activationRequired: "Activation requise",
    activationDesc: "Veuillez entrer votre clé de produit pour activer OfficeSuite.",
    keyUsed: "Cette clé a déjà été utilisée",
    activationSuccess: "Activé avec succès!",
    search: "Rechercher...",
    noDocuments: "Aucun document",
    createFirst: "Créez votre premier document",
    lastModified: "Dernière modification",
    type: "Type",
    bold: "Gras",
    italic: "Italique",
    underline: "Souligné",
    alignLeft: "Aligner à gauche",
    alignCenter: "Centrer",
    alignRight: "Aligner à droite",
    addRow: "Ajouter une ligne",
    addColumn: "Ajouter une colonne",
    addSlide: "Ajouter une diapositive",
    slide: "Diapositive",
    formula: "Formule",
    back: "Retour",
    saving: "Enregistrement...",
    saved: "Enregistré",
    german: "Allemand",
    english: "Anglais",
    french: "Français",
    spanish: "Espagnol",
    italian: "Italien"
  },
  es: {
    welcome: "Bienvenido a OfficeSuite",
    documents: "Documentos",
    spreadsheets: "Hojas de cálculo",
    presentations: "Presentaciones",
    newDocument: "Nuevo documento",
    newSpreadsheet: "Nueva hoja",
    newPresentation: "Nueva presentación",
    recent: "Reciente",
    favorites: "Favoritos",
    settings: "Configuración",
    language: "Idioma",
    theme: "Tema",
    light: "Claro",
    dark: "Oscuro",
    activate: "Activar",
    productKey: "Clave de producto",
    enterKey: "Ingrese la clave",
    activateNow: "Activar ahora",
    invalidKey: "Clave de producto inválida",
    activated: "Activado",
    save: "Guardar",
    delete: "Eliminar",
    rename: "Renombrar",
    cancel: "Cancelar",
    create: "Crear",
    title: "Título",
    untitled: "Sin título",
    allDocuments: "Todos los documentos",
    home: "Inicio",
    editor: "Editor",
    logout: "Cerrar sesión",
    activationRequired: "Activación requerida",
    activationDesc: "Por favor ingrese su clave de producto para activar OfficeSuite.",
    keyUsed: "Esta clave ya ha sido utilizada",
    activationSuccess: "¡Activado exitosamente!",
    search: "Buscar...",
    noDocuments: "Sin documentos",
    createFirst: "Cree su primer documento",
    lastModified: "Última modificación",
    type: "Tipo",
    bold: "Negrita",
    italic: "Cursiva",
    underline: "Subrayado",
    alignLeft: "Alinear izquierda",
    alignCenter: "Centrar",
    alignRight: "Alinear derecha",
    addRow: "Agregar fila",
    addColumn: "Agregar columna",
    addSlide: "Agregar diapositiva",
    slide: "Diapositiva",
    formula: "Fórmula",
    back: "Volver",
    saving: "Guardando...",
    saved: "Guardado",
    german: "Alemán",
    english: "Inglés",
    french: "Francés",
    spanish: "Español",
    italian: "Italiano"
  },
  it: {
    welcome: "Benvenuto in OfficeSuite",
    documents: "Documenti",
    spreadsheets: "Fogli di calcolo",
    presentations: "Presentazioni",
    newDocument: "Nuovo documento",
    newSpreadsheet: "Nuovo foglio",
    newPresentation: "Nuova presentazione",
    recent: "Recente",
    favorites: "Preferiti",
    settings: "Impostazioni",
    language: "Lingua",
    theme: "Tema",
    light: "Chiaro",
    dark: "Scuro",
    activate: "Attiva",
    productKey: "Codice prodotto",
    enterKey: "Inserisci il codice",
    activateNow: "Attiva ora",
    invalidKey: "Codice prodotto non valido",
    activated: "Attivato",
    save: "Salva",
    delete: "Elimina",
    rename: "Rinomina",
    cancel: "Annulla",
    create: "Crea",
    title: "Titolo",
    untitled: "Senza titolo",
    allDocuments: "Tutti i documenti",
    home: "Home",
    editor: "Editor",
    logout: "Esci",
    activationRequired: "Attivazione richiesta",
    activationDesc: "Inserisci il tuo codice prodotto per attivare OfficeSuite.",
    keyUsed: "Questo codice è già stato utilizzato",
    activationSuccess: "Attivato con successo!",
    search: "Cerca...",
    noDocuments: "Nessun documento",
    createFirst: "Crea il tuo primo documento",
    lastModified: "Ultima modifica",
    type: "Tipo",
    bold: "Grassetto",
    italic: "Corsivo",
    underline: "Sottolineato",
    alignLeft: "Allinea a sinistra",
    alignCenter: "Centra",
    alignRight: "Allinea a destra",
    addRow: "Aggiungi riga",
    addColumn: "Aggiungi colonna",
    addSlide: "Aggiungi diapositiva",
    slide: "Diapositiva",
    formula: "Formula",
    back: "Indietro",
    saving: "Salvataggio...",
    saved: "Salvato",
    german: "Tedesco",
    english: "Inglese",
    french: "Francese",
    spanish: "Spagnolo",
    italian: "Italiano"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children, initialLanguage = 'de' }) {
  const [language, setLanguage] = useState(initialLanguage);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
